runtime: python27
api_version: 1
threadsafe: true

default_expiration: "15m"

handlers:
# index files
- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /(.*)
  static_files: \1
  upload: (.*)

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$