runtime: python27
api_version: 1
threadsafe: true

default_expiration: "15m"

handlers:
# Handle folder urls by serving the index.html page inside.
- url: /(.*)/$
  static_files: \1/index.html
  upload: .*/index.html
  require_matching_file: true

# Index files.
- url: /([^.]+)/?$  # urls with no dot in them
  static_files: \1/index.html
  upload: (.+)/index.html
  require_matching_file: true
  expiration: "15m"

# Site root.
- url: /
  static_files: index.html
  upload: index.html
  secure: always

# All other files.
- url: /(.*)
  require_matching_file: true
  static_files: \1
  upload: (.*)

# All other files.
- url: /(.*)
  static_files: 404.html
  upload: 404.html

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
